### ISSUE TITLE
Diffusion

### ISSUE THREAD

**Issue by Chantec** [ChrisDud0257/SSL#3]
Thank you for your wonderful job!
Could you provide the code related to the DM version？

**Comment by ChrisDud0257** [comment]
> Thank you for your wonderful job! Could you provide the code related to the DM version？

Yes, we will update the code of SSL in Diffusion-model these days.

**Comment by Chantec** [comment]
> > Thank you for your wonderful job! Could you provide the code related to the DM version？
> 
> Yes, we will update the code of SSL in Diffusion-model these days.

Thanks!

**Comment by ChrisDud0257** [comment]
> > > Thank you for your wonderful job! Could you provide the code related to the DM version？
> > 
> > 
> > Yes, we will update the code of SSL in Diffusion-model these days.
> 
> Thanks!

I have uploaded the code of SSL in Diffusion-based models. Please find it at: https://github.com/ChrisDud0257/SSL/tree/main/Diffusion-Based-SR
