### ISSUE TITLE
Access to google drive GAN models

### ISSUE THREAD

**Issue by zelenooki87** [ChrisDud0257/SSL#9]
https://drive.google.com/drive/folders/17_4Ux74sdYEsHB1Zy9f1iTgJWyPW5Fyz?usp=drive_link
Could you allow sharing to public

**Comment by ChrisDud0257** [comment]
> https://drive.google.com/drive/folders/17_4Ux74sdYEsHB1Zy9f1iTgJWyPW5Fyz?usp=drive_link Could you allow sharing to public

Yes now I have made them public.

**Comment by profile838** [comment]
Thank you very much! :) great project :))
